-- Type of document

insert into home_document values('00', 'Otros (especificar)');
insert into home_document values('01', 'Factura');
insert into home_document values('02', 'Recibo por Honorarios');
insert into home_document values('03', 'Boleta de Venta');
insert into home_document values('04', 'Liquidación de compra');
insert into home_document values('05', 'Boleto de compañía de aviación comercial por el servicio de transporte aéreo de pasajeros');
insert into home_document values('06', 'Carta de porte aéreo por el servicio de transporte de carga aérea');
insert into home_document values('07', 'Nota de crédito');
insert into home_document values('08', 'Nota de débito');
insert into home_document values('09', 'Guía de remisión - Remitente');
insert into home_document values('10', 'Recibo por Arrendamiento');
insert into home_document values('11', 'Póliza emitida por las Bolsas de Valores, Bolsas de Productos o Agentes de Intermediación por operaciones realizadas en las Bolsas de Valores o Productos fuera de las mismas, autorizadas por CONASEV');
insert into home_document values('12', 'Ticket o cinta emitido por máquina registradora');
insert into home_document values('13', 'Documento emitido por bancos, instituciones financieras, crediticias y de seguros que se encuentren bajo el control de la Superintendencia de Banca y Seguros');
insert into home_document values('14', 'Recibo por servicios públicos de suministro de energía eléctrica, agua, teléfono, telex y telegráficos y otros servicios complementarios que se incluyan en el recibo de servicio público');
insert into home_document values('15', 'Boleto emitido por las empresas de transporte público urbano de pasajeros');
insert into home_document values('16', 'Boleto de viaje emitido por las empresas de transporte público interprovincial de pasajeros dentro del país');
insert into home_document values('17', 'Documento emitido por la Iglesia Católica por el arrendamiento de bienes inmuebles');
insert into home_document values('18', 'Documento emitido por las Administradoras Privadas de Fondo de Pensiones que se encuentran bajo la supervisión de la Superintendencia de Administradoras Privadas de Fondos de Pensiones');
insert into home_document values('19', 'Boleto o entrada por atracciones y espectáculos públicos');
insert into home_document values('20', 'Comprobante de Retención');
insert into home_document values('21', 'Conocimiento de embarque por el servicio de transporte de carga marítima');
insert into home_document values('22', 'Comprobante por Operaciones No Habituales');
insert into home_document values('23', 'Pólizas de Adjudicación emitidas con ocasión del remate o adjudicación de bienes por venta forzada, por los martilleros o las entidades que rematen o subasten bienes por cuenta de terceros');
insert into home_document values('24', 'Certificado de pago de regalías emitidas por PERUPETRO S.A');
insert into home_document values('25', 'Documento de Atribución (Ley del Impuesto General a las Ventas e Impuesto Selectivo al Consumo, Art. 19º, último párrafo, R.S. N° 022-98-SUNAT).');
insert into home_document values('26', 'Recibo por el Pago de la Tarifa por Uso de Agua Superficial con fines agrarios y por el pago de la Cuota para la ejecución de una determinada obra o actividad acordada por la Asamblea General de la Comisión de Regantes o Resolución expedida por el Jefe de la Unidad de Aguas y de Riego (Decreto Supremo N° 003-90-AG, Arts. 28 y 48)');
insert into home_document values('27', 'Seguro Complementario de Trabajo de Riesgo');
insert into home_document values('28', 'Tarifa Unificada de Uso de Aeropuerto');
insert into home_document values('29', 'Documentos emitidos por la COFOPRI en calidad de oferta de venta de terrenos, los correspondientes a las subastas públicas y a la retribución de los servicios que presta');
insert into home_document values('30', 'Documentos emitidos por las empresas que desempeñan el rol adquirente en los sistemas de pago mediante tarjetas de crédito y débito');
insert into home_document values('31', 'Guía de Remisión - Transportista');
insert into home_document values('32', 'Documentos emitidos por las empresas recaudadoras de la denominada Garantía de Red Principal a la que hace referencia el numeral 7.6 del artículo 7° de la Ley N° 27133 – Ley de Promoción del Desarrollo de la Industria del Gas Natural');
insert into home_document values('34', 'Documento del Operador');
insert into home_document values('35', 'Documento del Partícipe');
insert into home_document values('36', 'Recibo de Distribución de Gas Natural');
insert into home_document values('37', 'Documentos que emitan los concesionarios del servicio de revisiones técnicas vehiculares, por la prestación de dicho servicio');
insert into home_document values('50', 'Declaración Única de Aduanas - Importación definitiva');
insert into home_document values('52', 'Despacho Simplificado - Importación Simplificada');
insert into home_document values('53', 'Declaración de Mensajería o Courier');
insert into home_document values('54', 'Liquidación de Cobranza');
insert into home_document values('87', 'Nota de Crédito Especial');
insert into home_document values('88', 'Nota de Débito Especial');
insert into home_document values('91', 'Comprobante de No Domiciliado');
insert into home_document values('96', 'Exceso de crédito fiscal por retiro de bienes');
insert into home_document values('97', 'Nota de Crédito - No Domiciliado');
insert into home_document values('98', 'Nota de Débito - No Domiciliado');
insert into home_document values('99', 'Otros -Consolidado de Boletas de Venta');

-- Type of transaction
insert into home_operation values('01', 'VENTA');
insert into home_operation values('02', 'COMPRA');
insert into home_operation values('03', 'CONSIGNACIÓN RECIBIDA');
insert into home_operation values('04', 'CONSIGNACIÓN ENTREGADA');
insert into home_operation values('05', 'DEVOLUCIÓN RECIBIDA');
insert into home_operation values('06', 'DEVOLUCIÓN ENTREGADA');
insert into home_operation values('07', 'PROMOCIÓN');
insert into home_operation values('08', 'PREMIO');
insert into home_operation values('09', 'DONACIÓN');
insert into home_operation values('10', 'SALIDA A PRODUCCIÓN');
insert into home_operation values('11', 'TRANSFERENCIA ENTRE ALMACENES');
insert into home_operation values('12', 'RETIRO');
insert into home_operation values('13', 'MERMAS');
insert into home_operation values('14', 'DESMEDROS');
insert into home_operation values('15', 'DESTRUCCIÓN');
insert into home_operation values('16', 'SALDO INICIAL');
insert into home_operation values('99', 'OTROS (ESPECIFICAR)');
